// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Database;

#nullable disable

namespace Reporting.Database.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260920155150_ReportViewState")]
    partial class ReportViewState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Database.AccessGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("SecurableType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("SecurableType", "FolderId", "ReportId", "SubjectType", "UserId", "UserGroupId")
                        .IsUnique();

                    b.ToTable("AccessGrants", t =>
                        {
                            t.HasCheckConstraint("CK_AccessGrant_Securable", "([SecurableType] = 'Folder' AND [FolderId] IS NOT NULL AND [ReportId] IS NULL) OR ([SecurableType] = 'Report' AND [ReportId] IS NOT NULL AND [FolderId] IS NULL) OR ([SecurableType] = 'Root' AND [FolderId] IS NULL AND [ReportId] IS NULL)");

                            t.HasCheckConstraint("CK_AccessGrant_Subject", "([SubjectType] = 'User' AND [UserId] IS NOT NULL AND [UserGroupId] IS NULL) OR ([SubjectType] = 'Group' AND [UserGroupId] IS NOT NULL AND [UserId] IS NULL) OR ([SubjectType] = 'Everyone' AND [UserId] IS NULL AND [UserGroupId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Reporting.Database.AppPermissionGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Permission", "UserId")
                        .IsUnique();

                    b.ToTable("AppPermissionGrants");
                });

            modelBuilder.Entity("Reporting.Database.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportRevisionId")
                        .HasColumnType("int");

                    b.Property<string>("SourceConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.HasKey("Id");

                    b.HasIndex("DatasetSourceId");

                    b.HasIndex("ReportRevisionId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("Reporting.Database.DatasetCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("float");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId", "DateValue")
                        .HasFilter("[DateValue] IS NOT NULL");

                    b.HasIndex("ColumnId", "NumberValue")
                        .HasFilter("[NumberValue] IS NOT NULL");

                    b.HasIndex("ColumnId", "StringValue")
                        .HasFilter("[StringValue] IS NOT NULL");

                    b.HasIndex("RowId", "ColumnId")
                        .IsUnique();

                    b.ToTable("DatasetCells");
                });

            modelBuilder.Entity("Reporting.Database.DatasetColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "RefId")
                        .IsUnique();

                    b.ToTable("DatasetColumns");
                });

            modelBuilder.Entity("Reporting.Database.DatasetRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "RefId")
                        .IsUnique();

                    b.ToTable("DatasetRows");
                });

            modelBuilder.Entity("Reporting.Database.DatasetSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DatasetSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "Assembly",
                            Name = "Assembly"
                        },
                        new
                        {
                            Id = 2,
                            Key = "Disassembly",
                            Name = "Disassembly"
                        },
                        new
                        {
                            Id = 3,
                            Key = "Specification",
                            Name = "Specification"
                        });
                });

            modelBuilder.Entity("Reporting.Database.FilterOperatorDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperandCount")
                        .HasColumnType("int");

                    b.Property<string>("OperandKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColumnType", "Operator")
                        .IsUnique();

                    b.ToTable("FilterOperatorDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnType = "String",
                            Label = "is",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "Equals",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            ColumnType = "String",
                            Label = "is not",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "NotEquals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            ColumnType = "String",
                            Label = "contains",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "Contains",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            ColumnType = "String",
                            Label = "does not contain",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "NotContains",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            ColumnType = "String",
                            Label = "starts with",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "StartsWith",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            ColumnType = "String",
                            Label = "ends with",
                            OperandCount = 1,
                            OperandKind = "Text",
                            Operator = "EndsWith",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            ColumnType = "String",
                            Label = "is any of",
                            OperandCount = 1,
                            OperandKind = "List",
                            Operator = "In",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            ColumnType = "String",
                            Label = "is empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsEmpty",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            ColumnType = "String",
                            Label = "is not empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsNotEmpty",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            ColumnType = "Int",
                            Label = "=",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "Equals",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 11,
                            ColumnType = "Int",
                            Label = "≠",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "NotEquals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            ColumnType = "Int",
                            Label = ">",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "GreaterThan",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            ColumnType = "Int",
                            Label = "≥",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "GreaterThanOrEqual",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 14,
                            ColumnType = "Int",
                            Label = "<",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "LessThan",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 15,
                            ColumnType = "Int",
                            Label = "≤",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "LessThanOrEqual",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 16,
                            ColumnType = "Int",
                            Label = "is between",
                            OperandCount = 2,
                            OperandKind = "Number",
                            Operator = "Between",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 17,
                            ColumnType = "Int",
                            Label = "is empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsEmpty",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 18,
                            ColumnType = "Int",
                            Label = "is not empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsNotEmpty",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 19,
                            ColumnType = "Int",
                            Label = "is in tolerance",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "InTolerance",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 20,
                            ColumnType = "Int",
                            Label = "needs concession",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "NeedsConcession",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 21,
                            ColumnType = "Int",
                            Label = "is out of tolerance",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "OutOfTolerance",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 22,
                            ColumnType = "Double",
                            Label = "=",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "Equals",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 23,
                            ColumnType = "Double",
                            Label = "≠",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "NotEquals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            ColumnType = "Double",
                            Label = ">",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "GreaterThan",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            ColumnType = "Double",
                            Label = "≥",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "GreaterThanOrEqual",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 26,
                            ColumnType = "Double",
                            Label = "<",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "LessThan",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 27,
                            ColumnType = "Double",
                            Label = "≤",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "LessThanOrEqual",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 28,
                            ColumnType = "Double",
                            Label = "is between",
                            OperandCount = 2,
                            OperandKind = "Number",
                            Operator = "Between",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 29,
                            ColumnType = "Double",
                            Label = "is empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsEmpty",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 30,
                            ColumnType = "Double",
                            Label = "is not empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsNotEmpty",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 31,
                            ColumnType = "Double",
                            Label = "is in tolerance",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "InTolerance",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 32,
                            ColumnType = "Double",
                            Label = "needs concession",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "NeedsConcession",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 33,
                            ColumnType = "Double",
                            Label = "is out of tolerance",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "OutOfTolerance",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 34,
                            ColumnType = "Bool",
                            Label = "is true",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsTrue",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 35,
                            ColumnType = "Bool",
                            Label = "is false",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsFalse",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 36,
                            ColumnType = "Bool",
                            Label = "is empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsEmpty",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 37,
                            ColumnType = "Bool",
                            Label = "is not empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsNotEmpty",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 38,
                            ColumnType = "DateTime",
                            Label = "is on",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "Equals",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 39,
                            ColumnType = "DateTime",
                            Label = "is not on",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "NotEquals",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 40,
                            ColumnType = "DateTime",
                            Label = "is after",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "GreaterThan",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 41,
                            ColumnType = "DateTime",
                            Label = "is on or after",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "GreaterThanOrEqual",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 42,
                            ColumnType = "DateTime",
                            Label = "is before",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "LessThan",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 43,
                            ColumnType = "DateTime",
                            Label = "is on or before",
                            OperandCount = 1,
                            OperandKind = "Date",
                            Operator = "LessThanOrEqual",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 44,
                            ColumnType = "DateTime",
                            Label = "is between",
                            OperandCount = 2,
                            OperandKind = "Date",
                            Operator = "Between",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 45,
                            ColumnType = "DateTime",
                            Label = "is in the last (days)",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "InLastDays",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 46,
                            ColumnType = "DateTime",
                            Label = "is in the next (days)",
                            OperandCount = 1,
                            OperandKind = "Number",
                            Operator = "InNextDays",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 47,
                            ColumnType = "DateTime",
                            Label = "is empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsEmpty",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 48,
                            ColumnType = "DateTime",
                            Label = "is not empty",
                            OperandCount = 0,
                            OperandKind = "None",
                            Operator = "IsNotEmpty",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("Reporting.Database.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InheritsPermissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Reporting.Database.GrantAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecurableId")
                        .HasColumnType("int");

                    b.Property<string>("SecurableType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SecurableType", "SecurableId", "CreatedAt");

                    b.ToTable("GrantAuditEntries");
                });

            modelBuilder.Entity("Reporting.Database.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<bool>("InheritsPermissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Reporting.Database.ReportFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId", "ReportId")
                        .IsUnique();

                    b.ToTable("ReportFavorites");
                });

            modelBuilder.Entity("Reporting.Database.ReportRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiltersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.HasIndex("ReportId");

                    b.ToTable("ReportRevisions");
                });

            modelBuilder.Entity("Reporting.Database.ReportView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId", "ReportId")
                        .IsUnique();

                    b.HasIndex("UserId", "ViewedAt");

                    b.ToTable("ReportViews");
                });

            modelBuilder.Entity("Reporting.Database.ReportViewState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId", "ReportId")
                        .IsUnique();

                    b.ToTable("ReportViewStates");
                });

            modelBuilder.Entity("Reporting.Database.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Columns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(48);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReportRevisionId")
                        .HasColumnType("int");

                    b.Property<int>("Rows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.HasKey("Id");

                    b.HasIndex("ReportRevisionId", "RefId")
                        .IsUnique();

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("Reporting.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsGlobalAdmin")
                        .HasColumnType("bit");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Reporting.Database.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RefId")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Reporting.Database.UserGroupManager", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupManagers");
                });

            modelBuilder.Entity("Reporting.Database.UserGroupMember", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMembers");
                });

            modelBuilder.Entity("Reporting.Database.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H")
                        .HasColumnType("int");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("W")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabId", "RefId")
                        .IsUnique();

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("Reporting.Database.AccessGrant", b =>
                {
                    b.HasOne("Reporting.Database.Folder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reporting.Database.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reporting.Database.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Reporting.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Reporting.Database.AppPermissionGrant", b =>
                {
                    b.HasOne("Reporting.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Database.Dataset", b =>
                {
                    b.HasOne("Reporting.Database.DatasetSource", "Source")
                        .WithMany()
                        .HasForeignKey("DatasetSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reporting.Database.ReportRevision", "ReportRevision")
                        .WithMany("Datasets")
                        .HasForeignKey("ReportRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportRevision");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Reporting.Database.DatasetCell", b =>
                {
                    b.HasOne("Reporting.Database.DatasetRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Reporting.Database.DatasetColumn", b =>
                {
                    b.HasOne("Reporting.Database.Dataset", "Dataset")
                        .WithMany("Columns")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Reporting.Database.DatasetRow", b =>
                {
                    b.HasOne("Reporting.Database.Dataset", "Dataset")
                        .WithMany("Rows")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Reporting.Database.Folder", b =>
                {
                    b.HasOne("Reporting.Database.Folder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("Reporting.Database.Report", b =>
                {
                    b.HasOne("Reporting.Database.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Reporting.Database.ReportFavorite", b =>
                {
                    b.HasOne("Reporting.Database.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reporting.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Database.ReportRevision", b =>
                {
                    b.HasOne("Reporting.Database.Report", "Report")
                        .WithMany("Revisions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Reporting.Database.ReportView", b =>
                {
                    b.HasOne("Reporting.Database.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reporting.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Database.ReportViewState", b =>
                {
                    b.HasOne("Reporting.Database.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reporting.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Database.Tab", b =>
                {
                    b.HasOne("Reporting.Database.ReportRevision", "ReportRevision")
                        .WithMany("Tabs")
                        .HasForeignKey("ReportRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportRevision");
                });

            modelBuilder.Entity("Reporting.Database.UserGroupManager", b =>
                {
                    b.HasOne("Reporting.Database.UserGroup", "UserGroup")
                        .WithMany("Managers")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reporting.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Reporting.Database.UserGroupMember", b =>
                {
                    b.HasOne("Reporting.Database.UserGroup", "UserGroup")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reporting.Database.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Reporting.Database.Widget", b =>
                {
                    b.HasOne("Reporting.Database.Tab", "Tab")
                        .WithMany("Widgets")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tab");
                });

            modelBuilder.Entity("Reporting.Database.Dataset", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Reporting.Database.DatasetRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("Reporting.Database.Report", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Reporting.Database.ReportRevision", b =>
                {
                    b.Navigation("Datasets");

                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("Reporting.Database.Tab", b =>
                {
                    b.Navigation("Widgets");
                });

            modelBuilder.Entity("Reporting.Database.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Reporting.Database.UserGroup", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
