namespace Reporting.Database;

/// <summary>
/// A single grid surface within a <see cref="ReportRevision"/>. A revision has one or more tabs,
/// each carrying its own grid dimensions and its own widgets, so different tabs can be shaped
/// independently.
/// </summary>
public class Tab
{
    public int Id { get; set; }

    /// <summary>
    /// Stable logical id, exposed through the API and generated by the client. Preserved when a
    /// revision is copied to a new version (like <see cref="Widget.RefId"/>), so a tab keeps its
    /// identity across versions even though its <see cref="Id"/> changes. Unique per revision.
    /// </summary>
    public Guid RefId { get; set; }

    public int ReportRevisionId { get; set; }
    public ReportRevision? ReportRevision { get; set; }

    public string Name { get; set; } = string.Empty;

    /// <summary>Position among the revision's tabs, ascending.</summary>
    public int Order { get; set; }

    public int Columns { get; set; } = 48;
    public int Rows { get; set; } = 30;

    public List<Widget> Widgets { get; set; } = new();
}
