using Reporting.Abstractions;

namespace Reporting.Database;

public class Widget
{
    public int Id { get; set; }

    /// <summary>
    /// Stable logical id, exposed through the API and generated by the client. Preserved when a
    /// revision is copied to a new version, so a widget keeps its identity across versions even though
    /// its <see cref="Id"/> changes. Unique per revision rather than globally.
    /// </summary>
    public Guid RefId { get; set; }

    public int ReportRevisionId { get; set; }
    public ReportRevision? ReportRevision { get; set; }
    public WidgetType Type { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
    public int W { get; set; }
    public int H { get; set; }

    // JSON-serialized widget-type-specific config (e.g. DataTableWidgetConfig).
    public string ConfigJson { get; set; } = "{}";
}
