// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Api.Data;

#nullable disable

namespace Reporting.Api.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Reporting.Api.Domain.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DatasetFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("DatasetFieldValues");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DatasetFieldValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Reporting.Api.Domain.DatasetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DatasetRecords");
                });

            modelBuilder.Entity("Reporting.Api.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Reporting.Api.Domain.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("W")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("Reporting.Api.Domain.BoolFieldValue", b =>
                {
                    b.HasBaseType("Reporting.Api.Domain.DatasetFieldValue");

                    b.HasDiscriminator().HasValue("BoolFieldValue");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DateTimeFieldValue", b =>
                {
                    b.HasBaseType("Reporting.Api.Domain.DatasetFieldValue");

                    b.HasDiscriminator().HasValue("DateTimeFieldValue");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DoubleFieldValue", b =>
                {
                    b.HasBaseType("Reporting.Api.Domain.DatasetFieldValue");

                    b.HasDiscriminator().HasValue("DoubleFieldValue");
                });

            modelBuilder.Entity("Reporting.Api.Domain.IntFieldValue", b =>
                {
                    b.HasBaseType("Reporting.Api.Domain.DatasetFieldValue");

                    b.HasDiscriminator().HasValue("IntFieldValue");
                });

            modelBuilder.Entity("Reporting.Api.Domain.StringFieldValue", b =>
                {
                    b.HasBaseType("Reporting.Api.Domain.DatasetFieldValue");

                    b.HasDiscriminator().HasValue("StringFieldValue");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DatasetFieldValue", b =>
                {
                    b.HasOne("Reporting.Api.Domain.DatasetRecord", "Record")
                        .WithMany("Fields")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DatasetRecord", b =>
                {
                    b.HasOne("Reporting.Api.Domain.Dataset", "Dataset")
                        .WithMany("Records")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Reporting.Api.Domain.Widget", b =>
                {
                    b.HasOne("Reporting.Api.Domain.Report", "Report")
                        .WithMany("Widgets")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Reporting.Api.Domain.Dataset", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Reporting.Api.Domain.DatasetRecord", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Reporting.Api.Domain.Report", b =>
                {
                    b.Navigation("Widgets");
                });
#pragma warning restore 612, 618
        }
    }
}
