import { ReportFilter } from '../filter';
import { AccessLevel } from '../permission';
import { Widget } from './widget.model';

/** A report's identity and folder placement — everything except its content. */
export interface ReportSummary {
  id: number;
  number: number;
  name: string;
  folderId: number | null;
  /**
   * Whether the report has a checked-out draft. The server only ever reports this as true to a
   * caller who can edit the report, so a viewer never learns a draft exists — treat it as an
   * editor-only signal.
   */
  hasDraft: boolean;
  latestVersionNumber: number | null;
  /** The current user's effective access to this report — drives whether editing is offered. */
  accessLevel: AccessLevel;
  /** Whether the current user has starred this report. */
  isFavorite: boolean;
  modifiedAt: string;
}

/** One tab of a revision: a grid surface with its own dimensions and widgets. */
export interface Tab {
  /** Stable logical id (the entity's RefId), generated by the client. */
  id: string;
  name: string;
  order: number;
  columns: number;
  rows: number;
  widgets: Widget[];
}

/** The content of one revision of a report — either the checked-out draft or one published version. */
export interface ReportRevisionContent {
  reportId: number;
  name: string;
  /** The revision's tabs, ordered; each carries its own grid and widgets. */
  tabs: Tab[];
  /** Rich-text (HTML) description of what changed. Null for drafts. */
  notes: string | null;
  /** Report-level filters, one per dataset, applied on top of each widget's own. */
  filters: ReportFilter[];
}

export interface ReportVersionSummary {
  versionNumber: number;
  publishedAt: string;
  /** Rich-text (HTML) description of what changed in this version, entered when publishing. */
  notes: string | null;
}

/** A report match from a name/number search, with its folder location for display. */
export interface ReportSearchResult {
  id: number;
  number: number;
  name: string;
  /** Editor-only signal — see {@link ReportSummary.hasDraft}. */
  hasDraft: boolean;
  latestVersionNumber: number | null;
  /** The current user's effective access to this report — drives whether editing is offered. */
  accessLevel: AccessLevel;
  /** Whether the current user has starred this report. */
  isFavorite: boolean;
  modifiedAt: string;
  folderPath: string;
}
